---

- name: run tasks and role firewall on Fortigate
  hosts: fg
  gather_facts: no
  vars:
    - fw_select_file: files/fw_select.csv
    - _fw_selected: []
    - _zone: ""
    - local_rule: "{{ fw_rule }}"
    - fw_rules: []
    - _token: "{{ fw_access_token }}"

  tasks:
    - name: only run once block
      block:
      - name: read select file
        read_csv:
          path: "{{ fw_select_file }}"
          delimiter: ';'
          key: 'subnet'
          unique: true
        register: _fw_select_dict
        delegate_to: localhost
      
      - debug: 
          var: _fw_select_dict
          verbosity: 2

  # design decision: only the first source and destination are taken to select firewalls
      - name: select Firewall for Source
        set_fact:
          _fw_selected: "{{ _fw_selected + [_fw_select_dict.dict[local_rule.src.addresses[0].ipv4 | ansible.utils.ipsubnet(16,0)].fw] }}"
      - name: select Firewall for Destination
        set_fact:
          _fw_selected: "{{ _fw_selected + [_fw_select_dict.dict[local_rule.dest.addresses[0].ipv4 | ansible.utils.ipsubnet(16,0)].fw] }}"
      
      - name: firwalls selected for deployment
        debug:
          var: _fw_selected
      
      - name: get zone for src address
        ansible.builtin.include_tasks: 
          file: fg_routingtable.yml
        vars:
          - srcip: "{{ local_rule.src.addresses[0].ipv4 }}"
          - script_path: '/tmp/fgt.shell.src.task'
          
      - set_fact:
          _tmpvar: "{{ local_rule['src'] | combine( {'zone': _zone}) }}" 
          _src_intf: "{{ _intf }}"
      - set_fact:
          local_rule: "{{ local_rule | combine( {'src': _tmpvar }, list_merge='replace') }}"
        
      - name: get zone for dest address
        ansible.builtin.include_tasks: 
          file: fg_routingtable.yml
        vars:
          - srcip: "{{ local_rule.dest.addresses[0].ipv4 }}"
          - script_path: '/tmp/fgt.shell.dest.task'

      - set_fact:
          _tmpvar: "{{ local_rule['dest'] | combine( {'zone': _zone}) }}" 
      - set_fact:
          local_rule: "{{ local_rule | combine( {'dest': _tmpvar }, list_merge='replace') }}"
      
      - name: print local rule
        debug: 
          var: local_rule
          verbosity: 2

      - name: start rulecheck 
        ansible.builtin.include_tasks: 
          file: fg_rulecheck.yml
        vars:
          - script_path: '/tmp/fgt.shell.rule.task'

      run_once: true 
      # block finished

    - set_fact:
        fw_rules: "{{ fw_rules + [ local_rule ] }}"

    - name: start executing generic firewall role
      ansible.builtin.include_role: 
        name: firewall_generic
        apply: 
          tags: 
            - rule
      when: inventory_hostname in _fw_selected
        